version: '3'
services:
  api:
    build: ./api
    volumes:
      - ./api:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 3002:3002
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=3002
      - HOST=0.0.0.0
      - NODE_ENV=development
      - APP_KEY=3vlNXXhbckXg3VYhb1G8KLRaL0xvbPUF
      - CACHE_VIEWS=false
      - DRIVE_DISK=local
      - DB_CONNECTION=pg
      - PG_HOST=db
      - PG_PORT=5432
      - PG_USER=adonis
      - PG_PASSWORD=adonis
      - PG_DB_NAME=adonis
      - WALLET_LOCATION=wallets
      - BLOCKCHAIN_ENVIRONMENT=production
      - BLOCKCHAIN=ethereum
      - PROVIDER_URL=wss://goerli.infura.io/ws/v3/${INFURA_PROJECT_ID}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - DAML_JWT_SECRET=${DAML_JWT_SECRET}
      - ADMIN_PASSWORD=UNIQUE_VALUE_1
    depends_on:
      - db
    command: 
      - sh
      - -c
      - |
          node ace migration:run &&
          npm run dev

  dashboard:
    stdin_open: true
    build: ./dashboard
    volumes:
      - ./dashboard:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 3000:3000
    environment:
      - REACT_APP_WL_CONTRACT_DEPLOYMENT_URL=http://localhost:3002/
      - REACT_APP_PROVIDER_URL=wss://goerli.infura.io/ws/v3/${INFURA_PROJECT_ID}
      - REACT_APP_API_URL=http://localhost:3002/
      - REACT_APP_WEBSOCKET=ws://localhost:3002
    depends_on:
      - db
      - api
    command: npm start

  admin:
    build: ./admin
    volumes:
      - ./admin:/home/node/app
      - ./infra/.env.admin:/home/node/app/.env
      - /home/node/app/node_modules
    ports:
      - 3001:4200
    depends_on:
      - db
      - api
    command: npm start

  db:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=adonis
      - POSTGRES_PASSWORD=adonis
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local